#Exercícios

###Aluno: Katlyn Ribeiro Almeida           
###Nusp:14586070
1 - Implemente uma classe que permita selecionar o conjunto de treinamento e teste. Use o código abaixo para verificar se sua implementação está funcionando.

In [40]:
#acredito que separar os imports antes do codigo auxilia na melhor compreenção do codigo
import numpy as np
from scipy.spatial import distance
import statistics

In [45]:
#Trecho do código citado na questão retirado do notebook-poo ---------------------------
def create_matrix(n_rows, m_cols):
    matrix = np.zeros((n_rows, m_cols)) # Initialize with correct dimensions
    for i in range(n_rows):
        matrix[i,:] = i # Set all elements in row i to i
    return matrix

# Exemplo de uso da função:
n_rows = 10 # Número de linhas
m_cols = 4 # Número de colunas

print('Matriz X:')
X = create_matrix(n_rows, m_cols)
# Exibindo a matriz
for row in X:
    print(row)

print('Vetor y:')
y = create_matrix(n_rows, 1)
# Exibindo a matriz
for row in y:
    print(row)
#------------------------------------------------------------------------------



#codigo alterado para mostrar se de fato funciona a classe de separar o treino do teste
#ex: 0.4 é 40% do total
altera = separa_treino_e_teste(tam_treino=0.4)
treino_x, teste_x, treino_y, teste_y = altera.corte(X, y)

#aqui irá exibir os treinos
print("--- exibir treinos ---")
for row_x, row_y in zip(treino_x, treino_y):
    print(f"X: {row_x} | y: {row_y}")

#aqui irá exibir os testes
print("--- exibir testes ---")
for row_x, row_y in zip(teste_x, teste_y):
    print(f"X: {row_x} | y: {row_y}")

Matriz X:
[0. 0. 0. 0.]
[1. 1. 1. 1.]
[2. 2. 2. 2.]
[3. 3. 3. 3.]
[4. 4. 4. 4.]
[5. 5. 5. 5.]
[6. 6. 6. 6.]
[7. 7. 7. 7.]
[8. 8. 8. 8.]
[9. 9. 9. 9.]
Vetor y:
[0.]
[1.]
[2.]
[3.]
[4.]
[5.]
[6.]
[7.]
[8.]
[9.]
--- exibir treinos ---
X: [0. 0. 0. 0.] | y: [0.]
X: [1. 1. 1. 1.] | y: [1.]
X: [2. 2. 2. 2.] | y: [2.]
X: [3. 3. 3. 3.] | y: [3.]
--- exibir testes ---
X: [4. 4. 4. 4.] | y: [4.]
X: [5. 5. 5. 5.] | y: [5.]
X: [6. 6. 6. 6.] | y: [6.]
X: [7. 7. 7. 7.] | y: [7.]
X: [8. 8. 8. 8.] | y: [8.]
X: [9. 9. 9. 9.] | y: [9.]


In [42]:
#Abaixo se encontra o código referenta a questão 1----------------------------
class separa_treino_e_teste:

    def __init__(self, tam_treino):
        self.tam_treino = tam_treino

    def corte(self, X, y):
        #aqui calcula o indice onde o corte vai ser feito
        corte_x = int(len(X) * self.tam_treino)

        #optei por usar o fatiamento para separar os dados de treino e teste
        treino_x = X[:corte_x]
        teste_x = X[corte_x:]
        treino_y = y[:corte_x]
        teste_y = y[corte_x:]

        return treino_x, teste_x, treino_y, teste_y

2 - Consider o código abaixo que implementa o classificador k-vizinhos. Crie uma classe que permite realizar a classificação. Implemente o métodos predict, bem como outros disponíveis no scikit-learn:
https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html




###Os atributos deve ser X, y, k e a distância. O método deve ser o predict.

In [53]:
#Trecho do código citado na questão retirado do notebook-poo ---------------------------
def knn(x_train, y_train, x_test, k):
    distances = [] #lista que armazena as distâncias
    x1 = x_test # elemento a ser classificado
    for x2 in x_train: # distancia entre a observacao elementos no conjunto de teste
        dist = distance.euclidean(x1,x2)
        distances.append(dist)
    indices = []
    cl = []
    for i in range(0,k):
        ind = np.argmin(distances) #elemento no conjunto de teste mais proximo
        #print('distance:', distances[ind],'index:', ind, 'class:', y_train[ind])
        distances[ind] = np.max(distances)
        indices.append(ind)
        cl.append(y_train[ind]) #guarda a classe
    print("Classes:",cl)
    classification = statistics.mode(cl)# encontra a classe
    return classification
    #-------------------------------------------------------------------------------

In [56]:
#Abaixo se encontra o codigo referente a questao 2----------------------------------
class knn_editado:
    def __init__(self, n_neighbors=3, metric='euclidean'):
        self.n_neighbors = n_neighbors
        self.metric = metric
        self.X_train = None
        self.y_train = None

    #armazena dados de treinamento
    def fit(self, X, y):
        self.X_train = np.array(X)
        self.y_train = np.array(y)
        return self

    #metodo para classificar um único ponto baseado no codigo entregue no enunciado
    def uma_pred(self, x_test):
        distancias = []
        #distância entre o ponto de teste e todos os pontos de treino
        for x_train_row in self.X_train:
                dist = distance.euclidean(x_test, x_train_row)

        temp_distancias = list(distancias)
        cl = []

        for _ in range(self.n_neighbors):
            ind = np.argmin(temp_distancias)
            cl.append(self.y_train[ind])
            temp_distancias[ind] = np.max(temp_distancias)

        #no final do metodo retorna a classe mais frequente
        return statistics.mode(cl)

    #metodo que faz a predição para um conjunto de dados
    def predict(self, teste_x):
        teste_x = np.array(teste_x)
        predicao = [self.uma_pred(x) for x in teste_x]
        return np.array(predicao)